# Generated by Django 5.1.4 on 2026-08-01 00:35

import core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('contato', models.CharField(max_length=255, validators=[core.validators.validate_contato], verbose_name='contato')),
                ('logo_url', models.URLField(blank=True, max_length=500, validators=[core.validators.validate_logo_url], verbose_name='logo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunidades_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'comunidade',
                'verbose_name_plural': 'comunidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ComunidadeMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('organizador', 'Organizador'), ('membro', 'Membro')], default='membro', max_length=20)),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membros_adicionados', to=settings.AUTH_USER_MODEL)),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_vinculo', to='core.comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_comunidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro da comunidade',
                'verbose_name_plural': 'membros da comunidade',
                'ordering': ['adicionado_em'],
            },
        ),
        migrations.AddField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(related_name='comunidades', through='core.ComunidadeMembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='hora de fim')),
                ('local', models.CharField(max_length=300, verbose_name='local')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], max_length=20, verbose_name='tipo')),
                ('url_online', models.URLField(blank=True, max_length=500, verbose_name='URL online')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.comunidade', verbose_name='comunidade')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='organizador')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='comunidademembro',
            constraint=models.UniqueConstraint(fields=('comunidade', 'usuario'), name='unique_membro_por_comunidade'),
        ),
        migrations.AddConstraint(
            model_name='comunidade',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='unique_comunidade_nome_ci'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('comunidade', 'titulo', 'data'), name='unique_evento_titulo_data_por_comunidade'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__isnull', True), ('hora_fim__gt', models.F('hora_inicio')), _connector='OR'), name='evento_hora_fim_apos_hora_inicio'),
        ),
    ]
