# Generated by Django 6.0.7 on 2026-08-01 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='membros',
            field=models.ManyToManyField(related_name='comunidades', through='core.ComunidadeMembro', through_fields=('comunidade', 'usuario'), to=settings.AUTH_USER_MODEL),
        ),
    ]
